# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsSwitch < Formula
  desc "Fast, user-friendly TUI for quickly switching between DNS configurations"
  homepage "https://github.com/pinaka-io/dns-switch"
  version "1.0.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.4/dns-switch-darwin-amd64.tar.gz"
      sha256 "9c350510fa72f48a292752dc3988a795573b0e4755be4c419e78beb076afa8e0"

      define_method(:install) do
        bin.install "dns-switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.4/dns-switch-darwin-arm64.tar.gz"
      sha256 "7ce297d1858f248a070b121bc6df60c38a33835bcad4f249425b4fad67a66d50"

      define_method(:install) do
        bin.install "dns-switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.4/dns-switch-linux-amd64.tar.gz"
      sha256 "531e0a9cff96cd07bd77b4981d8d0dffadc21a0757d375d9159d472f382f419e"
      define_method(:install) do
        bin.install "dns-switch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.4/dns-switch-linux-arm64.tar.gz"
      sha256 "1d0f025b46a149d4ea65ed2f7ad8a85614a241cd2922fe6608ee7358a009f64d"
      define_method(:install) do
        bin.install "dns-switch"
      end
    end
  end

  def post_install
    config_dir = Pathname.new(ENV["HOME"]).join(".config", "dns-switch")
    config_dir.mkpath
    config_file = config_dir.join("config.yaml")
    unless config_file.exist?
      File.write(config_file, <<~EOS)
        # DNS Switch Configuration
        # Add your DNS profiles here

        dns_profiles:
          # Adguard DNS
          adguard:
            name: "AdGuard DNS"
            description: "AdGuard DNS for blocking ads and trackers"
            primary: "192.168.4.69"
            secondary: ""

          # Cloudflare DNS
          cloudflare:
            name: "Cloudflare (1.1.1.1)"
            description: "Fast and privacy-focused DNS"
            primary: "1.1.1.1"
            secondary: "1.0.0.1"

          # Google DNS
          google:
            name: "Google Public DNS"
            description: "Reliable DNS by Google"
            primary: "8.8.8.8"
            secondary: "8.8.4.4"

          # Quad9 DNS
          quad9:
            name: "Quad9 (Security)"
            description: "DNS with malware blocking"
            primary: "9.9.9.9"
            secondary: "149.112.112.112"

          # OpenDNS
          opendns:
            name: "OpenDNS"
            description: "Fast and reliable DNS"
            primary: "208.67.222.222"
            secondary: "208.67.220.220"

          # DHCP (Automatic)
          dhcp:
            name: "DHCP (Automatic)"
            description: "Use DNS provided by your network"
            primary: "auto"
            secondary: "auto"

        # Network interface to configure (e.g., "Wi-Fi", "Ethernet", "en0")
        # Leave empty to show a list of available interfaces
        network_interface: ""
      EOS
      puts "Default config file created at #{config_file}"
    end
  end

  def caveats
    <<~EOS
      DNS Switch requires sudo to modify network settings:
        sudo dns-switch

      Configuration file location:
        ~/.config/dns-switch/config.yaml
    EOS
  end

  test do
    system "#{bin}/dns-switch --version"
  end
end
