# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DnsSwitch < Formula
  desc "Fast, user-friendly TUI for quickly switching between DNS configurations"
  homepage "https://github.com/pinaka-io/dns-switch"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.2/dns-switch-darwin-amd64.tar.gz"
      sha256 "4311e1c31e772dd9afdb96c459ce835959529b4256cf1fcf5fdaae7f408badbd"

      define_method(:install) do
        bin.install "dns-switch"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.2/dns-switch-darwin-arm64.tar.gz"
      sha256 "becdfe7c76b8c242ee86f1001bbc1f379909af16172671a27e5dd35e6d11338d"

      define_method(:install) do
        bin.install "dns-switch"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.2/dns-switch-linux-amd64.tar.gz"
      sha256 "eecb83baded8d38dcb6d7544ebd5741a68cc12f5c67f747504754c91f6959128"
      define_method(:install) do
        bin.install "dns-switch"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pinaka-io/dns-switch/releases/download/v1.0.2/dns-switch-linux-arm64.tar.gz"
      sha256 "9d70bb5c1a946b79cd7ad3ac7cf65d16b7e95a56d677d6ee59d519bf1a1cd85a"
      define_method(:install) do
        bin.install "dns-switch"
      end
    end
  end

  def caveats
    <<~EOS
      DNS Switch requires sudo to modify network settings:
        sudo dns-switch

      Configuration file location:
        ~/.config/dns-switch/config.yaml
    EOS
  end

  test do
    system "#{bin}/dns-switch --version"
  end
end
