# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortForward < Formula
  desc "A lightweight CLI tool for managing SSH port forwarding tunnels"
  homepage "https://github.com/nishantapatil3/port-forward"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-darwin-amd64.tar.gz"
      sha256 "3d0856ef2a0f7b405ccbc16eaf99ac45787b281c1bb6e6cb9a2d35771cd7cf7e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-darwin-arm64.tar.gz"
      sha256 "91f328c5d1335a5db0fdcc1e42dbaea4835828eb887e560f0b7aa4790cd2f5ff"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-linux-amd64.tar.gz"
      sha256 "119bcae7b4c6e5e42ccf16966a5114e63e34e919cd49c94027aa70b1e384301e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-linux-arm64.tar.gz"
      sha256 "e8e568c524ce2a60a0ec391317654d446334543218e3da41b2795071998cacb8"
    end
  end

  def install
    bin.install "port-forward"
  end

  def caveats
    <<~EOS
      Port Forward manages SSH tunnels through configuration:

      Configuration file location:
        ~/.config/port-forward/config.yaml
    EOS
  end

  test do
    system "#{bin}/port-forward --version"
  end
end
