# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PortForward < Formula
  desc "A lightweight CLI tool for managing SSH port forwarding tunnels"
  homepage "https://github.com/nishantapatil3/port-forward"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-darwin-amd64.tar.gz"
      sha256 "504ab4bf2983a7be71499b2d0f7713b5f193ec3866717f44d7d09a66a7737850"

      define_method(:install) do
        bin.install "port-forward"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-darwin-arm64.tar.gz"
      sha256 "fa8c415cfed9a4371915ef9e427e9e6e2cab353a926c11f93865a4181c08486e"

      define_method(:install) do
        bin.install "port-forward"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-linux-amd64.tar.gz"
      sha256 "4d336d7b74784e38bd6ee17efc91e8f0005c45a7922c383f5b8a8838a4450362"
      define_method(:install) do
        bin.install "port-forward"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/nishantapatil3/port-forward/releases/download/v1.0.0/port-forward-linux-arm64.tar.gz"
      sha256 "4c5687ed696c17c5c5be155aee39a9858b6e2e99b419a174ecf716b060cf2b57"
      define_method(:install) do
        bin.install "port-forward"
      end
    end
  end

  def caveats
    <<~EOS
      Port Forward manages SSH tunnels through configuration:

      Configuration file location:
        ~/.config/port-forward/config.yaml
    EOS
  end

  test do
    system "#{bin}/port-forward --version"
  end
end
