# typed: false
# frozen_string_literal: true

# This file will be auto-generated by GoReleaser on first release.
# To install: brew tap nishantapatil3/homebrew-tap && brew install port-forward
class PortForward < Formula
  desc "A lightweight CLI tool for managing SSH port forwarding tunnels"
  homepage "https://github.com/nishantapatil3/port-forward"
  version "0.0.1"
  license "MIT"

  # This formula will be populated by goreleaser when you create the first release
  # Run: git tag -a v1.0.0 -m "Release v1.0.0" && git push origin v1.0.0

  def install
    bin.install "port-forward"
  end

  def caveats
    <<~EOS
      Port Forward manages SSH tunnels through configuration:

      Configuration file location:
        ~/.config/port-forward/config.yaml
    EOS
  end

  test do
    system "#{bin}/port-forward --version"
  end
end
